package Constants;
import static Constants.URLConstants.*;
public class URLConstants {
    public static  String BOOTSTRAP_CSS="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css",
            HEADER_FILE="/WEB-INF/LayoutTemplates/LayoutHeader.jsp",
            FOOTER_FILE="/WEB-INF/LayoutTemplates/LayoutFooter.jsp",
            RETRIEVE_DATA_CSS="/ServletAndJava_war_exploded/resource/CSS/RetrieveData.css",
            RETRIEVE_PAGE="/WEB-INF/Views/RetrieveData.jsp",
            BACKGROUND_IMG_SRC ="/ServletAndJava_war_exploded/resource/frenzzy_files/background.jpeg",
            DIGITAL_LOGO="/ServletAndJava_war_exploded/resource/images/iconfirst.png",
            DESKTOP_BG_IMG="/ServletAndJava_war_exploded/resource/frenzzy_files/borrower_2div_ghvugv.png",
            MOBILE_BG_IMG="/ServletAndJava_war_exploded/resource/frenzzy_files/borrowermid_fuyhtd.png",
            CEO_IMG="/ServletAndJava_war_exploded/resource/frenzzy_files/amit_ihskhe.jpg",
            LOGIN_PAGE_URL="/WEB-INF/Views/LoginPage.jsp",
            LOGIN_PAGE_CSS="/ServletAndJava_war_exploded/resource/CSS/LoginPage.css",
            SUCCESS_PAGE_CSS="/ServletAndJava_war_exploded/resource/CSS/sucess.css",
            ADMIN_PAGE="./admin.jsp",
            ADMIN_CSS="/ServletAndJava_war_exploded/resource/CSS/admin.css",
            CONTACT_US_PAGE="/WEB-INF/Views/ContactUs.jsp",
            LANDING_PAGE_CSS="/ServletAndJava_war_exploded/resource/CSS/landingpage.css",
            CIO_IMG="/ServletAndJava_war_exploded/resource/frenzzy_files/apoorv_mt9lo0.jpg",
            CUSTOMER_UMA="/ServletAndJava_war_exploded/resource/frenzzy_files/uma-maheshwari.png",
            CONTACT_US_CSS="/ServletAndJava_war_exploded/resource/CSS/ContactUs.css",GET_RESULT="getData",
            LAYOUT_INDEX_PATH="home",
            CUSTOMER_BIKRAM="/ServletAndJava_war_exploded/resource/frenzzy_files/bikram-chatterjee.png",
            CUSTOMER_NAIDU="/ServletAndJava_war_exploded/resource/frenzzy_files/l-giri-naidu.png",
            YOUR_STORY_IMG="/ServletAndJava_war_exploded/resource/frenzzy_files/your-story_kcwnva.png",
            TIMES_OF_INDIA_IMG="/ServletAndJava_war_exploded/resource/frenzzy_files/times-of-india_iarzlk.png",
            INDIAN_EXPRESS_IMG="/ServletAndJava_war_exploded/resource/frenzzy_files/indian-express_skrqdd.png",
            ECONOMIC_TIMES_IMG="/ServletAndJava_war_exploded/resource/frenzzy_files/economic-times_msl8fl.png",
            BWCI_WORRLD_IMG="/ServletAndJava_war_exploded/resource/frenzzy_files/bw-ci-world_dfcyk3.png",
            TECH_HERALD_IMG="/ServletAndJava_war_exploded/resource/frenzzy_files/tech-herald_bnpn3o.png",
            CTO_IMG="/ServletAndJava_war_exploded/resource/frenzzy_files/abhinandan_aukpdl.jpg",
            CMO_IMG="/ServletAndJava_war_exploded/resource/frenzzy_files/vishwas_ztkchg.jpg",
            NAV_LOGO="/ServletAndJava_war_exploded/resource/frenzzy_files/logoWeb1x_1_thzngg.png",
            BADGE_LOGO="/ServletAndJava_war_exploded/resource/frenzzy_files/badge_small.png",
            LAYOUT_LOGIN_PAGE="/ServletAndJava_war_exploded/LoginPage.jsp",
            DOCUMENTATION_LOGO="/ServletAndJava_war_exploded/resource/images/iconsecond.png",
            EMI_LOGO="/ServletAndJava_war_exploded/resource/images/iconthird.png",
            REGISTER_URL="/WEB-INF/Views/Register.jsp",
            REGISTER_CSS="/ServletAndJava_war_exploded/resource/CSS/Register.css",
            REGISTER_SERVLET="RegisterUser",
            FORM_SUBMITTED_IMG="/ServletAndJava_war_exploded/resource/images/success.jpg",
            SUCCESS_REGISTERATION="/WEB-INF/Views/AdminRegistered.jsp",
            FORM_SUBMITTED="/WEB-INF/Views/FormSubmitted.jsp",
            CONTACT_US="/ServletAndJava_war_exploded/ContactForm";
}
