package Constants;
import static Constants.URLConstants.*;
public class URLConstants {
    public static  String BOOTSTRAP_CSS="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css",
            HEADER_FILE="LayoutTemplates/LayoutHeader.jsp",
            FOOTER_FILE="LayoutTemplates/LayoutFooter.jsp",
            RETRIEVE_DATA_CSS="CSS/RetrieveData.css",
            RETRIEVE_PAGE="./RetrieveData.jsp",
            BACKGROUND_IMG_SRC ="frenzzy_files/background.jpeg",
            DIGITAL_LOGO="images/iconfirst.png",
            DESKTOP_BG_IMG="frenzzy_files/borrower_2div_ghvugv.png",
            MOBILE_BG_IMG="frenzzy_files/borrowermid_fuyhtd.png",
            CEO_IMG="frenzzy_files/amit_ihskhe.jpg",
            LOGIN_PAGE_URL="./LoginPage.jsp",
            LOGIN_PAGE_CSS="CSS/LoginPage.css",
            SUCCESS_PAGE_CSS="CSS/sucess.css",
            ADMIN_PAGE="./admin.jsp",
            ADMIN_CSS="CSS/admin.css",
            CONTACT_US_PAGE="./ContactUs.jsp",
            LANDING_PAGE_CSS="CSS/landingpage.css",
            CIO_IMG="frenzzy_files/apoorv_mt9lo0.jpg",
            CUSTOMER_UMA="frenzzy_files/uma-maheshwari.png",
            CONTACT_US_CSS="CSS/ContactUs.css",GET_RESULT="getData",
            LAYOUT_INDEX_PATH="./",
            CUSTOMER_BIKRAM="frenzzy_files/bikram-chatterjee.png",
            CUSTOMER_NAIDU="frenzzy_files/l-giri-naidu.png",
            YOUR_STORY_IMG="frenzzy_files/your-story_kcwnva.png",
            TIMES_OF_INDIA_IMG="frenzzy_files/times-of-india_iarzlk.png",
            INDIAN_EXPRESS_IMG="frenzzy_files/indian-express_skrqdd.png",
            ECONOMIC_TIMES_IMG="frenzzy_files/economic-times_msl8fl.png",
            BWCI_WORRLD_IMG="frenzzy_files/bw-ci-world_dfcyk3.png",
            TECH_HERALD_IMG="frenzzy_files/tech-herald_bnpn3o.png",
            CTO_IMG="frenzzy_files/abhinandan_aukpdl.jpg",
            CMO_IMG="frenzzy_files/vishwas_ztkchg.jpg",
            NAV_LOGO="./frenzzy_files/logoWeb1x_1_thzngg.png",
            BADGE_LOGO="./frenzzy_files/badge_small.png",
            LAYOUT_LOGIN_PAGE="/ServletAndJava_war_exploded/LoginPage.jsp",
            DOCUMENTATION_LOGO="images/iconsecond.png",
            EMI_LOGO="images/iconthird.png",
            REGISTER_URL="./Register.jsp",
            REGISTER_SERVLET="RegisterUser",
            SUCCESS_REGISTERATION="./AdminRegistered.jsp",
            FORM_SUBMITTED="./FormSubmitted.jsp";
}
